#!/bin/bash
# Run this script after adding photos or videos to any folder.
# Generates photo_data.js which works on file:// protocol (no fetch needed).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PHOTOS_DIR="$SCRIPT_DIR/photos"
OUTPUT="$SCRIPT_DIR/photo_data.js"

echo "🌸 Scanning photo and video folders..."

python3 -c "
import os, json, sys

script_dir = sys.argv[1]
photos_dir = os.path.join(script_dir, 'photos')
output_file = os.path.join(script_dir, 'photo_data.js')

# Both image and video formats supported
EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.mp4', '.mov', '.webm', '.avi', '.mkv', '.m4v', '.3gp'}

data = {}

for root, dirs, files in os.walk(photos_dir):
    rel_path = os.path.relpath(root, photos_dir)
    if rel_path == '.':
        continue

    valid_files = []
    for f in sorted(files):
        name_lower = f.lower()
        is_valid = any(name_lower.endswith(ext) for ext in EXTS)
        if is_valid:
            valid_files.append(f)

    if valid_files:
        key = rel_path.replace(os.path.sep, '/')
        data[key] = valid_files
        status = '  \u2705  ' + key + ' \u2014 ' + str(len(valid_files)) + ' items'
        print(status)

js = '// AUTO-GENERATED by generate_manifests.sh \u2014 do not edit manually\n// Run the script again after adding new photos.\nconst PHOTO_DATA = ' + json.dumps(data, indent=2, ensure_ascii=False) + ';\n'

with open(output_file, 'w', encoding='utf-8') as fp:
    fp.write(js)

total = sum(len(v) for v in data.values())
print()
print('Done! photo_data.js written \u2014 ' + str(total) + ' total items across ' + str(len(data)) + ' folders.')
print('Refresh the website to see your photos and videos.')
" "$SCRIPT_DIR"

