#!/bin/bash
# Run this script after adding photos to any folder.
# Generates photo_data.js which works on file:// protocol (no fetch needed).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PHOTOS_DIR="$SCRIPT_DIR/photos"
OUTPUT="$SCRIPT_DIR/photo_data.js"

echo "🌸 Scanning photo folders..."

python3 - <<'PYEOF'
import os, json

script_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else os.getcwd()

# When called from bash, use env var
import sys
script_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
photos_dir = os.path.join(script_dir, "photos")
output_file = os.path.join(script_dir, "photo_data.js")

IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.JPG', '.JPEG', '.PNG', '.WEBP', '.GIF'}

data = {}

for folder in sorted(os.listdir(photos_dir)):
    folder_path = os.path.join(photos_dir, folder)
    if not os.path.isdir(folder_path):
        continue

    files = []
    for f in sorted(os.listdir(folder_path)):
        filepath = os.path.join(folder_path, f)
        if not os.path.isfile(filepath):
            continue
        # Check extension - handle double extensions like .jpg.jpeg
        _, ext = os.path.splitext(f)
        if ext.lower() in IMAGE_EXTS:
            files.append(f)
        elif '.' in f:
            # Handle double extensions like IMG_1125.jpg.jpeg
            parts = f.split('.')
            if len(parts) >= 3 and ('.' + parts[-1].lower()) in IMAGE_EXTS:
                files.append(f)

    data[folder] = files
    status = f"✅  {folder} — {len(files)} images" if files else f"⚠   {folder} — no images"
    print(status)

js_content = f"// AUTO-GENERATED — run generate_manifests.sh after adding photos\nconst PHOTO_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"

with open(output_file, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"\n✅ photo_data.js written with {sum(len(v) for v in data.values())} total images across {len(data)} folders.")
PYEOF
PYEOF_EXIT=$?

# Pass script dir as argument to python
python3 -c "
import os, json, sys

script_dir = sys.argv[1]
photos_dir = os.path.join(script_dir, 'photos')
output_file = os.path.join(script_dir, 'photo_data.js')

IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.JPG', '.JPEG', '.PNG', '.WEBP', '.GIF'}

data = {}

for folder in sorted(os.listdir(photos_dir)):
    folder_path = os.path.join(photos_dir, folder)
    if not os.path.isdir(folder_path):
        continue

    files = []
    for f in sorted(os.listdir(folder_path)):
        filepath = os.path.join(folder_path, f)
        if not os.path.isfile(filepath):
            continue
        name_lower = f.lower()
        # Check all known image extensions (including double-ext like .jpg.jpeg)
        is_image = any(name_lower.endswith(ext) for ext in ['.jpg','.jpeg','.png','.webp','.gif','.jpg.jpeg','.jpeg.jpg','.png.jpg'])
        if is_image:
            files.append(f)

    data[folder] = files
    status = '  \u2705  ' + folder + ' \u2014 ' + str(len(files)) + ' images' if files else '  \u26a0   ' + folder + ' \u2014 no images yet'
    print(status)

js = '// AUTO-GENERATED by generate_manifests.sh \u2014 do not edit manually\n// Run the script again after adding new photos.\nconst PHOTO_DATA = ' + json.dumps(data, indent=2, ensure_ascii=False) + ';\n'

with open(output_file, 'w', encoding='utf-8') as fp:
    fp.write(js)

total = sum(len(v) for v in data.values())
print()
print('Done! photo_data.js written \u2014 ' + str(total) + ' total images across ' + str(len(data)) + ' folders.')
print('Refresh the website to see your photos.')
" "$SCRIPT_DIR"
