// AUTO-GENERATED by generate_manifests.sh — do not edit manually
// Run the script again after adding new photos.
const PHOTO_DATA = {
  "fav-pics": [
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (1).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (10).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (11).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (12).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (13).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (14).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (2).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (3).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (4).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (5).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (6).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (7).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (8).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM (9).jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.53 PM.jpeg",
    "WhatsApp Image 2026-06-28 at 12.22.54 PM.jpeg"
  ],
  "first-meet-vizag": [],
  "flowers": [
    "IMG_0449.jpg",
    "IMG_1007.jpg",
    "IMG_1034.jpg",
    "IMG_1087.jpg",
    "IMG_1125.jpg.jpeg",
    "IMG_6983.jpg",
    "IMG_9246.GIF",
    "IMG_9258.jpg.jpeg",
    "IMG_9397.jpg",
    "WhatsApp Image 2026-06-28 at 12.07.26 PM (1).jpeg",
    "WhatsApp Image 2026-06-28 at 12.07.26 PM.jpeg"
  ],
  "fourth-meet-wedding": [],
  "love-confession": [
    "WhatsApp Image 2026-06-28 at 12.20.36 PM.jpeg"
  ],
  "second-meet-cafe": [],
  "third-meet-vizag": [],
  "video-calls": []
};
